name: Build Android APK & AAB with Gradle 7.6.3 and Java 17

on:
  push:
    branches: [ main, cursor/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: NDA-CALCULATOR   # 👈 Run inside project folder

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: '34'
        build-tools: '30.0.3'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 🟢 Clean before building so fresh artifacts are created
    - name: Clean Project
      run: ./gradlew clean

    # ✅ Build Debug APK
    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Debug APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: NDA-CALCULATOR/app/build/outputs/apk/debug/app-debug.apk

    # ✅ Build Release APK
    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload Release APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: NDA-CALCULATOR/app/build/outputs/apk/release/app-release.apk

    # ✅ Build Release AAB (App Bundle)
    - name: Build Release AAB
      run: ./gradlew bundleRelease

    - name: Upload Release AAB artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release-aab
        path: NDA-CALCULATOR/app/build/outputs/bundle/release/app-release.aab
